// Default tag database — keyed by lowercase plugin name.
// Applied automatically to any plugin with no tags after scan.
// User-set tags always take precedence.

const DEFAULT_TAGS = {

  // ── FabFilter ────────────────────────────────────────────────────────────────
  'pro-q 4':          ['eq', 'filter'],
  'pro-q 3':          ['eq', 'filter'],
  'pro-q 2':          ['eq', 'filter'],
  'pro-c 2':          ['comp', 'dynamic'],
  'pro-mb':           ['comp', 'multiband', 'dynamic'],
  'pro-r 2':          ['reverb', 'room', 'plate'],
  'pro-r':            ['reverb', 'room', 'plate'],
  'pro-ds':           ['de-esser', 'vocal', 'dynamic'],
  'pro-g':            ['gate', 'dynamic'],
  'pro-l 2':          ['limiter', 'mastering'],
  'pro-l':            ['limiter', 'mastering'],
  'saturn 2':         ['saturation', 'distortion', 'multiband'],
  'saturn':           ['saturation', 'distortion'],
  'timeless 3':       ['delay', 'pitch', 'filter'],
  'timeless 2':       ['delay', 'pitch', 'filter'],
  'volcano 3':        ['filter', 'sequencer'],
  'volcano 2':        ['filter', 'sequencer'],
  'twin 3':           ['synth', 'filter', 'additive'],
  'twin 2':           ['synth', 'filter', 'additive'],
  'one':              ['synth', 'sample-based', 'filter'],
  'micro':            ['synth', 'filter'],

  // ── Valhalla ─────────────────────────────────────────────────────────────────
  'valhalla room':            ['reverb', 'room'],
  'valhallaroom':             ['reverb', 'room'],
  'vintageverb':              ['reverb', 'room', 'vintage'],
  'valhallavintageverb':      ['reverb', 'room', 'vintage'],
  'valhalla vintage verb':    ['reverb', 'room', 'vintage'],
  'valhallashimmer':          ['reverb', 'pitch', 'ambient'],
  'valhalla shimmer':         ['reverb', 'pitch', 'ambient'],
  'valhalla plate':           ['reverb', 'plate'],
  'valhallaplate':            ['reverb', 'plate'],
  'valhallaplatemkii':        ['reverb', 'plate'],
  'valhalla delay':           ['delay', 'vintage', 'tape'],
  'valhalladelay':            ['delay', 'vintage', 'tape'],
  'valhallasupermassive':     ['reverb', 'delay', 'ambient'],
  'valhalla supermassive':    ['reverb', 'delay', 'ambient'],
  'valhalla freq echo':       ['delay', 'filter', 'pitch'],
  'valhallafreqecho':         ['delay', 'filter', 'pitch'],
  'valhallaubermod':          ['chorus', 'flanger', 'delay'],
  'valhalla ubermod':         ['chorus', 'flanger', 'delay'],
  'valhalla space modulator': ['flanger', 'ring-mod', 'pitch'],
  'valhallaspacemodulator':   ['flanger', 'ring-mod', 'pitch'],

  // ── iZotope ──────────────────────────────────────────────────────────────────
  'ozone 11':               ['mastering', 'eq', 'limiter', 'multiband'],
  'ozone 10':               ['mastering', 'eq', 'limiter', 'multiband'],
  'ozone 9':                ['mastering', 'eq', 'limiter', 'multiband'],
  'ozone 8':                ['mastering', 'eq', 'limiter', 'multiband'],
  'ozone':                  ['mastering', 'eq', 'limiter', 'multiband'],
  'neutron 4':              ['eq', 'comp', 'dynamic', 'multiband'],
  'neutron 3':              ['eq', 'comp', 'dynamic', 'multiband'],
  'neutron 2':              ['eq', 'comp', 'dynamic'],
  'neutron':                ['eq', 'comp', 'dynamic'],
  'nectar 4':               ['vocal', 'eq', 'comp', 'de-esser'],
  'nectar 3':               ['vocal', 'eq', 'comp', 'de-esser'],
  'nectar':                 ['vocal', 'eq', 'comp', 'de-esser'],
  'rx 11':                  ['noise', 'utility', 'spectral'],
  'rx 10':                  ['noise', 'utility', 'spectral'],
  'rx 9':                   ['noise', 'utility', 'spectral'],
  'rx':                     ['noise', 'utility', 'spectral'],
  'iris 2':                 ['synth', 'sample-based', 'spectral'],
  'trash 2':                ['distortion', 'multiband'],
  'stutter edit 2':         ['glitch', 'sequencer'],
  'stutter edit':           ['glitch', 'sequencer'],
  'vocalsynth 2':           ['vocal', 'vocoder', 'synth'],
  'vocalsynth':             ['vocal', 'vocoder', 'pitch'],
  'breaktweaker':           ['drum', 'glitch', 'sequencer'],
  'insight 2':              ['utility', 'mastering'],
  'insight':                ['utility', 'mastering'],
  'imager':                 ['imager', 'widener'],
  'dialogue match':         ['vocal', 'utility'],
  'rx de-noise':            ['noise', 'utility'],
  'rx de-click':            ['utility', 'noise'],
  'rx de-hum':              ['utility', 'noise'],
  'rx de-clip':             ['utility', 'dynamic'],
  'rx voice de-noise':      ['noise', 'vocal', 'utility'],
  'music rebalance':        ['utility', 'spectral'],
  'spectral repair':        ['utility', 'spectral'],

  // ── Native Instruments ───────────────────────────────────────────────────────
  'kontakt 7':          ['sample-based'],
  'kontakt 6':          ['sample-based'],
  'kontakt 5':          ['sample-based'],
  'kontakt':            ['sample-based'],
  'massive x':          ['synth', 'wavetable'],
  'massive':            ['synth', 'wavetable'],
  'fm8':                ['synth', 'fm'],
  'absynth 5':          ['synth', 'additive', 'granular'],
  'battery 4':          ['drum', 'sample-based'],
  'battery':            ['drum', 'sample-based'],
  'reaktor 6':          ['synth', 'multi-fx'],
  'reaktor':            ['synth', 'multi-fx'],
  'monark':             ['synth', 'analog', 'lead'],
  'replika xt':         ['delay', 'pitch', 'filter'],
  'replika':            ['delay'],
  'raum':               ['reverb', 'room'],
  'flair':              ['flanger', 'vintage'],
  'phasis':             ['phaser'],
  'choral':             ['chorus'],
  'supercharger gt':    ['comp', 'analog'],
  'supercharger':       ['comp', 'analog'],
  'transient master':   ['transient', 'dynamic'],
  'solid bus comp':     ['comp', 'bus', 'analog'],
  'solid dynamics':     ['comp', 'gate', 'dynamic'],
  'solid eq':           ['eq', 'analog'],
  'driver':             ['distortion', 'saturation'],
  'guitar rig 7':       ['multi-fx', 'distortion'],
  'guitar rig 6':       ['multi-fx', 'distortion'],
  'guitar rig 5':       ['multi-fx', 'distortion'],
  'una corda':          ['piano', 'physical-modeling', 'sample-based'],
  'noire':              ['piano', 'sample-based'],
  'the grandeur':       ['piano', 'sample-based'],
  'the giant':          ['piano', 'sample-based'],
  "alicia's keys":      ['piano', 'sample-based', 'keys'],
  'straylight':         ['pad', 'ambient', 'sample-based'],
  'pharlight':          ['pad', 'ambient', 'sample-based', 'vocal'],
  'arkhis':             ['pad', 'ambient', 'sample-based'],
  'kinetic toys':       ['pad', 'sample-based', 'granular'],
  'action strikes':     ['drum', 'sample-based'],
  'damage':             ['drum', 'sample-based'],
  'thrill':             ['ambient', 'sample-based'],
  'rise & hit':         ['drum', 'sample-based'],
  'form':               ['synth', 'sample-based', 'spectral'],
  'prism':              ['synth', 'spectral'],
  'blocks':             ['synth', 'multi-fx'],
  'analog dreams':      ['synth', 'sample-based', 'analog', 'vintage'],
  'hybrid keys':        ['keys', 'sample-based'],
  'session guitarist':  ['strings', 'sample-based', 'pluck'],
  'strummed acoustic':  ['strings', 'sample-based', 'pluck'],
  'scarbee rickenbacker bass': ['bass', 'sample-based', 'pluck'],
  'scarbee jay-bass':   ['bass', 'sample-based', 'pluck'],
  'scarbee mm-bass':    ['bass', 'sample-based', 'pluck'],
  'vintage organs':     ['organ', 'sample-based', 'vintage'],
  'george duke soul treasures': ['keys', 'sample-based', 'vintage'],
  'the gentleman':        ['piano', 'sample-based', 'vintage'],
  'the maverick':         ['piano', 'sample-based', 'vintage'],
  'session strings pro 2': ['strings', 'sample-based'],
  'session strings pro':  ['strings', 'sample-based'],
  'session horns pro':    ['brass', 'sample-based'],
  'session horns':        ['brass', 'sample-based'],
  'studio drummer':       ['drum', 'sample-based'],
  'drumlab':              ['drum', 'sample-based', 'synth'],
  'kinetic metal':        ['pad', 'sample-based'],
  'butch vig vocals':     ['vocal', 'sample-based'],
  'west africa':          ['drum', 'sample-based'],
  'abbey road 50s drummer': ['drum', 'sample-based', 'vintage'],
  'abbey road 60s drummer': ['drum', 'sample-based', 'vintage'],
  'abbey road 70s drummer': ['drum', 'sample-based', 'vintage'],
  'abbey road 80s drummer': ['drum', 'sample-based', 'vintage'],
  'indie drums':          ['drum', 'sample-based'],
  'symphobia 1':          ['strings', 'brass', 'sample-based'],
  'symphobia 2':          ['strings', 'brass', 'sample-based'],
  'komplete kontrol':     ['utility'],

  // ── Arturia — V Collection (instruments) ─────────────────────────────────────
  'analog lab v':        ['synth', 'sample-based', 'keys'],
  'analog lab':          ['synth', 'sample-based', 'keys'],
  'pigments':            ['synth', 'wavetable', 'granular', 'additive'],
  'mini v3':             ['synth', 'analog', 'vintage', 'lead'],
  'mini v':              ['synth', 'analog', 'vintage', 'lead'],
  'acid v':              ['synth', 'analog', 'bass', 'lead', 'vintage'],
  'sem v2':              ['synth', 'analog', 'vintage', 'filter'],
  'sem v':               ['synth', 'analog', 'vintage', 'filter'],
  'jup-8 v4':            ['synth', 'analog', 'vintage', 'pad'],
  'jup-8 v':             ['synth', 'analog', 'vintage', 'pad'],
  'jun-6 v':             ['synth', 'analog', 'vintage', 'chorus'],
  'juno-6 v':            ['synth', 'analog', 'vintage', 'chorus'],
  'matrix-12 v2':        ['synth', 'analog', 'vintage'],
  'matrix-12 v':         ['synth', 'analog', 'vintage'],
  'ob-xa v':             ['synth', 'analog', 'vintage', 'pad'],
  'prophet-5 v':         ['synth', 'analog', 'vintage'],
  'prophet-vs v':        ['synth', 'wavetable', 'vintage'],
  'prophet-600 v':       ['synth', 'analog', 'vintage'],
  'cs-80 v3':            ['synth', 'analog', 'vintage', 'pad'],
  'cs-80 v':             ['synth', 'analog', 'vintage', 'pad'],
  'arp 2600 v3':         ['synth', 'analog', 'vintage'],
  'arp 2600 v':          ['synth', 'analog', 'vintage'],
  'ms-20 v3':            ['synth', 'analog', 'vintage', 'filter'],
  'ms-20 v2':            ['synth', 'analog', 'vintage', 'filter'],
  'ms-20 v':             ['synth', 'analog', 'vintage', 'filter'],
  'modular v3':          ['synth', 'analog'],
  'modular v':           ['synth', 'analog'],
  'synthi v':            ['synth', 'analog', 'vintage'],
  'buchla easel v':      ['synth', 'physical-modeling'],
  'cmi v':               ['synth', 'sample-based', 'additive', 'vintage'],
  'synclavier v':        ['synth', 'additive', 'sample-based', 'vintage'],
  'emulator ii v':       ['synth', 'sample-based', 'vintage'],
  'dx7 v':               ['synth', 'fm', 'vintage'],
  'minibrute v':         ['synth', 'analog', 'lead'],
  'minifreak v':         ['synth', 'wavetable', 'fm'],
  'microfreak v':        ['synth', 'wavetable', 'physical-modeling'],
  'polybrute connect':   ['synth', 'analog'],
  'mellotron v':         ['sample-based', 'strings', 'vintage'],
  'piano v3':            ['piano', 'physical-modeling', 'sample-based'],
  'piano v2':            ['piano', 'physical-modeling', 'sample-based'],
  'piano v':             ['piano', 'physical-modeling', 'sample-based'],
  'stage-73 v2':         ['keys', 'sample-based', 'vintage'],
  'stage-73 v':          ['keys', 'sample-based', 'vintage'],
  'wurli v2':            ['keys', 'sample-based', 'vintage'],
  'wurli v':             ['keys', 'sample-based', 'vintage'],
  'clavinet v':          ['keys', 'sample-based', 'vintage'],
  'solina v2':           ['strings', 'sample-based', 'vintage', 'keys'],
  'solina v':            ['strings', 'sample-based', 'vintage', 'keys'],
  'farfisa v2':          ['organ', 'vintage', 'keys'],
  'farfisa v':           ['organ', 'vintage', 'keys'],
  'vox continental v2':  ['organ', 'vintage', 'keys'],
  'vox continental v':   ['organ', 'vintage', 'keys'],
  'b-3 v3':              ['organ', 'vintage'],
  'b-3 v2':              ['organ', 'vintage'],
  'b-3 v':               ['organ', 'vintage'],
  'augmented strings':         ['strings', 'sample-based', 'spectral'],
  'augmented brass':           ['brass', 'sample-based', 'spectral'],
  'augmented woodwinds':       ['sample-based', 'spectral'],
  'augmented voices':          ['vocal', 'sample-based', 'spectral'],
  'augmented piano':           ['piano', 'sample-based', 'spectral'],
  'augmented grand piano':     ['piano', 'sample-based', 'spectral'],
  'augmented guitars & basses':['strings', 'bass', 'sample-based'],
  'keylab':              ['utility'],

  // ── Arturia — FX Collection ───────────────────────────────────────────────────
  'comp diode-609':      ['comp', 'analog', 'vintage'],
  'comp vca-65':         ['comp', 'analog', 'vintage'],
  'comp tube-sta':       ['comp', 'analog', 'vintage', 'tube'],
  'comp fet-76':         ['comp', 'analog', 'vintage'],
  'eq sitral-295':       ['eq', 'analog', 'vintage'],
  'eq bax':              ['eq', 'analog', 'vintage'],
  'eq p1v':              ['eq', 'analog', 'vintage'],
  'eq hy3m':             ['eq', 'analog', 'vintage'],
  'pre trident':         ['saturation', 'analog', 'vintage'],
  'pre tridemt':         ['saturation', 'analog', 'vintage'],
  'pre 1973':            ['saturation', 'analog', 'vintage'],
  'pre v76':             ['saturation', 'analog', 'vintage', 'tube'],
  'rev lx-24':           ['reverb', 'analog', 'vintage'],
  'rev plate-140':       ['reverb', 'plate', 'vintage'],
  'rev spring-636':      ['reverb', 'spring', 'vintage', 'analog'],
  'delay tape-201':      ['delay', 'tape', 'vintage', 'analog'],
  'delay memory-brigade':['delay', 'analog', 'vintage'],
  'filter m12':          ['filter', 'analog', 'vintage'],
  'filter sem':          ['filter', 'analog', 'vintage'],
  'filter mini':         ['filter', 'analog', 'vintage'],
  'chorus jun-6':        ['chorus', 'analog', 'vintage'],
  'phaser bio-tron':     ['phaser', 'analog', 'vintage'],
  'flanger bl-20':       ['flanger', 'analog', 'vintage'],
  'bitcrusher m-machine':['bitcrusher', 'lo-fi'],
  'distortion tube-culture': ['distortion', 'saturation', 'tube', 'analog'],
  'amp jazz-cart':       ['distortion', 'analog', 'vintage'],
  'amp fire-scale':      ['distortion', 'analog'],
  'tape mello-fi':       ['saturation', 'tape', 'vintage', 'lo-fi'],

  // ── Soundtoys ────────────────────────────────────────────────────────────────
  'echoboy':          ['delay', 'vintage', 'saturation'],
  'echoboy jr':       ['delay', 'vintage'],
  'primaltap':        ['delay', 'vintage', 'lo-fi'],
  'crystallizer':     ['delay', 'pitch', 'granular'],
  'filterfreak 1':    ['filter', 'analog'],
  'filterfreak 2':    ['filter', 'analog'],
  'filterfreak':      ['filter', 'analog'],
  'tremolator':       ['tremolo'],
  'panman':           ['panning'],
  'little alterboy':  ['vocal', 'pitch', 'formant'],
  'little plate':     ['reverb', 'plate', 'vintage'],
  'microshift':       ['widener', 'pitch'],
  'radiator':         ['saturation', 'tube', 'vintage'],
  'sie-q':            ['eq', 'analog', 'vintage'],
  'decapitator':      ['saturation', 'distortion', 'analog'],
  'superplate':       ['reverb', 'plate'],
  'effect rack':      ['multi-fx'],
  'devil-loc':        ['saturation', 'comp', 'analog'],
  'devil-loc deluxe': ['saturation', 'comp', 'analog'],
  'crystals':         ['reverb', 'pitch'],
  'phasemistress':    ['phaser', 'vintage'],
  'speed':            ['tremolo', 'panning'],
  'wow & flutter':    ['saturation', 'tape', 'vintage'],

  // ── Waves ────────────────────────────────────────────────────────────────────
  'ssl e-channel':        ['eq', 'comp', 'analog', 'vintage'],
  'ssl g-master buss compressor': ['comp', 'bus', 'analog', 'vintage'],
  'ssl g-bus compressor': ['comp', 'bus', 'analog', 'vintage'],
  'cla-76':               ['comp', 'analog', 'vintage'],
  'cla-2a':               ['comp', 'analog', 'vintage'],
  'cla-3a':               ['comp', 'analog', 'vintage'],
  'api 2500':             ['comp', 'bus', 'analog'],
  'api 550a':             ['eq', 'analog', 'vintage'],
  'api 550b':             ['eq', 'analog', 'vintage'],
  'api 560':              ['eq', 'analog', 'vintage'],
  'v-eq3':                ['eq', 'analog', 'vintage'],
  'v-eq4':                ['eq', 'analog', 'vintage'],
  'v-comp':               ['comp', 'analog', 'vintage'],
  'v-series':             ['eq', 'comp', 'analog', 'vintage'],
  'pultec eqp-1a':        ['eq', 'analog', 'vintage'],
  'pultec meq-5':         ['eq', 'analog', 'vintage'],
  'renaissance compressor': ['comp', 'dynamic'],
  'renaissance equalizer':  ['eq', 'analog'],
  'renaissance bass':     ['bass', 'harmonic'],
  'renaissance channel':  ['eq', 'comp', 'analog'],
  'h-delay':              ['delay', 'vintage'],
  'h-reverb':             ['reverb', 'plate'],
  'h-comp':               ['comp', 'dynamic'],
  'h-eq':                 ['eq', 'analog'],
  'h-reverb long':        ['reverb', 'ambient'],
  'kramer master tape':   ['saturation', 'tape', 'vintage', 'lo-fi'],
  'kramer hls channel':   ['eq', 'analog', 'vintage'],
  'abbey road plates':    ['reverb', 'plate', 'vintage'],
  'abbey road chambers':  ['reverb', 'room', 'vintage'],
  'abbey road reverb plates': ['reverb', 'plate', 'vintage'],
  'abbey road studio 3':  ['reverb', 'room', 'vintage'],
  'abbey road rs124':     ['comp', 'analog', 'vintage'],
  'abbey road saturator': ['saturation', 'analog', 'vintage'],
  'abbey road vinyl':     ['saturation', 'lo-fi', 'vintage', 'noise'],
  'abbey road treble booster': ['eq', 'analog', 'vintage'],
  'l1 ultramaximizer':    ['limiter', 'mastering'],
  'l2 ultramaximizer':    ['limiter', 'mastering'],
  'l3 multimaximizer':    ['limiter', 'mastering', 'multiband'],
  'l3-ll multimaximizer': ['limiter', 'mastering', 'multiband'],
  'l3-16 multimaximizer': ['limiter', 'mastering', 'multiband'],
  'ir-1':                 ['reverb', 'convolution'],
  'ir-360':               ['reverb', 'convolution'],
  'deesser':              ['de-esser', 'vocal', 'dynamic'],
  'sibilance':            ['de-esser', 'vocal', 'dynamic'],
  'vocal rider':          ['vocal', 'dynamic', 'utility'],
  'bass rider':           ['bass', 'dynamic', 'utility'],
  'tune real-time':       ['pitch', 'vocal'],
  'tune':                 ['pitch', 'vocal'],
  'ovox':                 ['vocoder', 'vocal', 'pitch'],
  'morphoder':            ['vocoder', 'pitch'],
  'smack attack':         ['transient', 'dynamic'],
  'torque':               ['drum', 'transient'],
  'vitamin':              ['harmonic', 'exciter'],
  'aphex vintage aural exciter': ['exciter', 'harmonic', 'vintage'],
  'maxxbass':             ['bass', 'harmonic'],
  'loair':                ['bass', 'harmonic'],
  's1 stereo imager':     ['imager', 'widener'],
  'center':               ['imager', 'utility'],
  'mono':                 ['utility'],
  'inphase':              ['utility'],
  'paz analyzer':         ['utility'],
  'dorrough meter':       ['utility'],
  'wu-units':             ['comp', 'saturation', 'analog'],
  'j37 tape':             ['saturation', 'tape', 'vintage', 'lo-fi'],
  'puigchild 660':        ['comp', 'analog', 'vintage'],
  'puigchild 670':        ['comp', 'analog', 'vintage'],
  'scheps 73':            ['eq', 'analog', 'vintage'],
  'scheps 33609':         ['comp', 'bus', 'analog', 'vintage'],
  'scheps omni channel':  ['eq', 'comp', 'analog'],
  'dbx 160':              ['comp', 'analog', 'vintage'],
  'c1 compressor':        ['comp', 'dynamic', 'gate', 'sidechain'],
  'c4 multiband':         ['comp', 'multiband', 'dynamic'],
  'c6 multiband':         ['comp', 'multiband', 'dynamic'],
  'f6 floating-band dynamic eq': ['eq', 'dynamic', 'multiband'],
  'q10 paragraphic eq':   ['eq'],
  'linear phase eq':      ['eq', 'mastering'],
  'ps22 spread':          ['widener', 'imager'],
  'manny marroquin delay':    ['delay', 'vintage'],
  'manny marroquin distortion': ['distortion', 'saturation'],
  'manny marroquin eq':   ['eq'],
  'manny marroquin reverb': ['reverb'],
  'eddie kramer':         ['eq', 'comp', 'analog', 'vintage'],
  'cla unplugged':        ['comp', 'eq', 'analog'],
  'cla guitars':          ['comp', 'eq', 'saturation'],
  'cla bass':             ['comp', 'eq', 'bass'],
  'cla vocals':           ['comp', 'eq', 'vocal', 'de-esser'],
  'cla drums':            ['comp', 'eq', 'drum', 'transient'],
  'cla mixhub':           ['eq', 'comp', 'analog', 'mix'],
  'brauer motion':        ['panning', 'tremolo'],
  'submarine':            ['bass', 'harmonic'],
  'uv22hr':               ['utility', 'mastering'],
  'soundshifter':         ['pitch', 'utility'],
  'doppler':              ['pitch', 'imager'],
  'multirack native':     ['utility'],
  'nx ocean way nashville': ['reverb', 'room', 'vintage'],
  'nx virtual mix room':  ['reverb', 'room'],
  'greg wells tonecentric': ['eq', 'harmonic', 'analog'],
  'greg wells voicecentric': ['eq', 'comp', 'vocal'],
  'infected mushroom pusher': ['comp', 'dynamic'],
  'infected mushroom pancake 2000': ['saturation', 'analog'],
  'trans-x wide':         ['transient', 'dynamic'],
  'trans-x multi':        ['transient', 'dynamic', 'multiband'],
  'renaissance reverb':   ['reverb', 'room'],
  'trueverb':             ['reverb', 'room'],
  'rverb':                ['reverb'],
  'ns1 noise suppressor': ['noise', 'utility', 'gate'],
  'clarity vx':           ['vocal', 'noise', 'utility'],
  'clarity vx pro':       ['vocal', 'noise', 'utility'],
  'vocal bender':         ['vocal', 'pitch'],
  'rvox':                 ['vocal', 'comp', 'gate'],
  'r-vox':                ['vocal', 'comp', 'gate'],
  'rbass':                ['bass', 'harmonic'],
  'codex':                ['synth', 'wavetable', 'additive'],
  'ssl ev2 channel':      ['eq', 'comp', 'analog', 'vintage'],
  'manny marroquin triple d': ['de-esser', 'saturation', 'dynamic'],
  'redd 17':              ['eq', 'saturation', 'analog', 'vintage'],
  'redd 51':              ['eq', 'saturation', 'analog', 'vintage'],
  'oneknob brighter':     ['eq', 'exciter'],
  'oneknob louder':       ['limiter', 'harmonic'],
  'oneknob phatter':      ['bass', 'harmonic'],
  'oneknob filter':       ['filter'],
  'oneknob pumper':       ['sidechain', 'dynamic'],
  'puigtec eqp-1a':       ['eq', 'analog', 'vintage'],

  // ── Xfer Records ─────────────────────────────────────────────────────────────
  'serum':          ['synth', 'wavetable'],
  'ott':            ['comp', 'multiband', 'dynamic'],
  'cthulhu':        ['sequencer', 'pitch'],
  'lfo tool':       ['mod', 'sidechain', 'utility'],

  // ── u-he ─────────────────────────────────────────────────────────────────────
  'diva':       ['synth', 'analog', 'vintage'],
  'zebra2':     ['synth', 'wavetable', 'additive'],
  'zebra3':     ['synth', 'wavetable', 'additive'],
  'hive 2':     ['synth', 'wavetable'],
  'hive':       ['synth', 'wavetable'],
  'repro-1':    ['synth', 'analog', 'vintage', 'lead'],
  'repro-5':    ['synth', 'analog', 'vintage'],
  'ace':        ['synth', 'analog'],
  'bazille':    ['synth', 'fm', 'additive'],
  'triple cheese': ['synth', 'wavetable'],
  'podolski':   ['synth', 'analog'],
  'satin':      ['saturation', 'tape'],
  'presswerk':  ['comp', 'dynamic'],
  'uhbik-a':    ['reverb', 'spectral'],
  'uhbik-s':    ['chorus'],
  'uhbik-g':    ['granular'],
  'uhbik-d':    ['delay'],
  'uhbik-t':    ['tremolo'],
  'uhbik-p':    ['phaser'],
  'uhbik-f':    ['flanger'],
  'uhbik-q':    ['filter'],
  'filterscape': ['filter', 'sequencer'],
  'colour copy': ['delay', 'analog', 'chorus'],

  // ── Kilohearts ────────────────────────────────────────────────────────────────
  'phase plant':  ['synth', 'wavetable', 'granular', 'additive'],
  'snap heap':    ['multi-fx', 'filter'],
  'multipass':    ['multi-fx', 'multiband'],

  // ── Surge XT ─────────────────────────────────────────────────────────────────
  'surge xt':     ['synth', 'wavetable'],
  'surge':        ['synth', 'wavetable'],

  // ── Vital ────────────────────────────────────────────────────────────────────
  'vital':        ['synth', 'wavetable'],

  // ── Rob Papen ────────────────────────────────────────────────────────────────
  'predator 3':   ['synth', 'wavetable', 'fm'],
  'predator 2':   ['synth', 'wavetable', 'fm'],
  'predator':     ['synth', 'wavetable', 'fm'],
  'blue-iii':     ['synth', 'fm', 'additive'],
  'blue ii':      ['synth', 'fm', 'additive'],
  'raw':          ['distortion', 'saturation'],
  'quad':         ['delay', 'chorus'],
  'punch':        ['drum', 'sample-based'],
  'blade':        ['synth', 'additive'],
  'subboombass':  ['bass', 'synth'],

  // ── Spectrasonics ────────────────────────────────────────────────────────────
  'omnisphere 2': ['synth', 'sample-based', 'granular', 'wavetable'],
  'omnisphere':   ['synth', 'sample-based', 'granular', 'wavetable'],
  'stylus rmx':   ['drum', 'sample-based'],
  'trilian':      ['bass', 'sample-based'],
  'keyscape':     ['piano', 'keys', 'sample-based', 'vintage'],

  // ── Output ───────────────────────────────────────────────────────────────────
  'thermal':      ['distortion', 'multiband'],
  'portal':       ['granular', 'spectral'],
  'movement':     ['mod', 'sequencer', 'sidechain'],
  'exhaust':      ['distortion', 'saturation'],
  'signal':       ['sequencer', 'mod'],
  'analog strings': ['strings', 'sample-based', 'vintage'],
  'substance':    ['bass', 'sample-based'],

  // ── Eventide ─────────────────────────────────────────────────────────────────
  'h3000 band delays':  ['delay', 'pitch', 'multi-fx'],
  'h3000 factory':      ['pitch', 'delay', 'multi-fx'],
  'h910 harmonizer':    ['pitch', 'vintage'],
  'h949 harmonizer':    ['pitch', 'vintage'],
  'blackhole':          ['reverb', 'ambient'],
  'ultrareverb':        ['reverb', 'multi-fx'],
  'quadravox':          ['pitch', 'vocal'],
  'omnipressor':        ['comp', 'dynamic'],
  'micropitch':         ['pitch', 'widener'],
  'sp2016 reverb':      ['reverb', 'vintage'],
  'crystals':           ['reverb', 'pitch'],
  'phaser':             ['phaser'],
  'chorus':             ['chorus'],
  'flanger':            ['flanger'],
  'ultrachannel':       ['eq', 'comp', 'multi-fx'],
  'tverb':              ['reverb', 'room'],

  // ── Celemony ─────────────────────────────────────────────────────────────────
  'melodyne 5':         ['pitch', 'vocal', 'utility'],
  'melodyne 4':         ['pitch', 'vocal', 'utility'],
  'melodyne':           ['pitch', 'vocal', 'utility'],

  // ── Antares ──────────────────────────────────────────────────────────────────
  'auto-tune pro x':    ['pitch', 'vocal'],
  'auto-tune pro':      ['pitch', 'vocal'],
  'auto-tune artist':   ['pitch', 'vocal'],
  'auto-tune efx+':     ['pitch', 'vocal', 'glitch'],
  'auto-tune access':   ['pitch', 'vocal'],
  'harmony engine':     ['pitch', 'vocal'],
  'vocal doubler':      ['vocal', 'widener'],
  'avox evo':           ['vocal', 'multi-fx'],
  // AVOX Evo individual plugins (shown with "avox" prefix in DAWs)
  'avox throat':        ['vocal', 'formant', 'physical-modeling'],
  'avox duo':           ['vocal', 'widener'],
  'avox choir':         ['vocal', 'choir', 'pitch'],
  'avox punch':         ['vocal', 'dynamic', 'transient'],
  'avox articulator':   ['vocoder', 'vocal'],
  'avox aspire':        ['vocal', 'noise'],
  'avox mutator':       ['vocal', 'distortion'],
  'throat':             ['vocal', 'formant', 'physical-modeling'],

  // ── Softube ──────────────────────────────────────────────────────────────────
  'saturation knob':    ['saturation'],
  'console 1 channel':  ['eq', 'comp', 'analog'],
  'tube-tech cl 1b':    ['comp', 'analog', 'vintage', 'tube'],
  'tube-tech me 1b':    ['eq', 'analog', 'vintage', 'tube'],
  'tube-tech pe 1c':    ['eq', 'analog', 'vintage', 'tube'],
  'valley people dyna-mite': ['comp', 'gate', 'dynamic'],
  'transient shaper':   ['transient', 'dynamic'],
  'fix doubler':        ['vocal', 'widener'],
  'spring reverb':      ['reverb', 'spring', 'vintage'],
  'fix flanger & doubler': ['flanger', 'widener'],
  'harmonics':          ['saturation', 'harmonic', 'analog'],
  'model 80 eq':        ['eq', 'analog', 'vintage'],
  'weiss ds1-mk3':      ['comp', 'mastering', 'de-esser', 'dynamic'],
  'weiss eq1':          ['eq', 'mastering'],
  'weiss mm-1':         ['limiter', 'mastering'],
  'weiss gamut2':       ['mastering', 'utility'],
  'drawmer 1973':       ['comp', 'multiband', 'analog'],
  'drawmer s73':        ['comp', 'mastering'],
  'tsar-1':             ['reverb', 'room'],
  'tsar-1r':            ['reverb', 'room'],
  'high end compression': ['comp', 'analog'],

  // ── Sonnox ───────────────────────────────────────────────────────────────────
  'oxford eq':          ['eq'],
  'oxford dynamics':    ['comp', 'gate', 'dynamic'],
  'oxford reverb':      ['reverb'],
  'oxford inflator':    ['harmonic', 'exciter'],
  'oxford limiter v3':  ['limiter', 'mastering'],
  'oxford limiter':     ['limiter', 'mastering'],
  'oxford supresser':   ['de-esser', 'vocal', 'dynamic'],
  'oxford transmod':    ['transient', 'dynamic'],
  'oxford drum gate':   ['gate', 'drum'],
  'envolution':         ['transient', 'dynamic'],

  // ── Plugin Alliance / brainworx ──────────────────────────────────────────────
  'bx_digital v3':      ['eq', 'mastering', 'imager'],
  'bx_digital':         ['eq', 'mastering', 'imager'],
  'bx_console ssl 4000 e': ['eq', 'comp', 'analog', 'vintage'],
  'bx_console neve 8078': ['eq', 'comp', 'analog', 'vintage'],
  'bx_console neve 8200': ['eq', 'comp', 'analog', 'vintage'],
  'bx_console ssl 9000':  ['eq', 'comp', 'analog'],
  'bx_subfilter':       ['bass', 'filter'],
  'bx_saturator v2':    ['saturation'],
  'bx_masterdesk':      ['mastering', 'comp', 'eq'],
  'bx_limiter true peak': ['limiter', 'mastering'],
  'bx_opto compressor': ['comp', 'analog'],
  'bx_rockrack v3':     ['multi-fx', 'distortion'],
  'shadow hills mastering compressor': ['comp', 'mastering', 'analog'],
  'elysia alpha compressor': ['comp', 'mastering'],
  'elysia mpressor':    ['comp', 'dynamic'],
  'elysia niveau filter': ['eq', 'filter'],
  'maag eq4':           ['eq', 'analog'],
  'api 550a':           ['eq', 'analog', 'vintage'],
  'sly-fi kaya':        ['reverb', 'room'],
  'sly-fi deflector':   ['chorus'],
  'amek eq 200':        ['eq', 'analog', 'vintage'],
  'chandler limited germ 500 bcm': ['eq', 'analog', 'vintage'],

  // ── Slate Digital ────────────────────────────────────────────────────────────
  'fg-x mastering processor': ['limiter', 'mastering'],
  'fg-x':               ['limiter', 'mastering'],
  'trigger 2':          ['drum', 'transient', 'sample-based'],
  'trigger':            ['drum', 'transient', 'sample-based'],
  'virtual tape machines': ['saturation', 'tape', 'vintage'],
  'fresh air':          ['harmonic', 'exciter', 'eq'],
  'virtual mix rack':   ['eq', 'comp', 'analog', 'vintage'],
  'fg-116':             ['comp', 'analog', 'vintage'],
  'fg-2a':              ['comp', 'analog', 'vintage'],
  'fg-grey':            ['comp', 'bus', 'analog', 'vintage'],
  'fg-stress':          ['comp', 'analog'],
  'fg-bomber':          ['comp', 'saturation', 'analog'],
  'fg-d':               ['eq', 'analog'],
  'fg-n':               ['eq', 'analog', 'vintage'],
  'fg-s':               ['eq', 'analog', 'vintage'],
  'fg-a':               ['eq', 'analog'],
  'ml-1':               ['comp', 'limiter'],
  'infinity eq':        ['eq'],
  'lo air':             ['bass', 'harmonic'],

  // ── UAD / Universal Audio ────────────────────────────────────────────────────
  'ua 1176 rev a':          ['comp', 'analog', 'vintage'],
  'ua 1176 rev e':          ['comp', 'analog', 'vintage'],
  'ua 1176 rev a limiting amp': ['comp', 'analog', 'vintage'],
  '1176 limiting amp':      ['comp', 'analog', 'vintage'],
  '1176ln limiting amp':    ['comp', 'analog', 'vintage'],
  'la-2a compressor':       ['comp', 'analog', 'vintage'],
  'la-2a leveling amplifier': ['comp', 'analog', 'vintage'],
  'la-3a audio leveler':    ['comp', 'analog', 'vintage'],
  'teletronix la-2a':       ['comp', 'analog', 'vintage'],
  'neve 1073':              ['eq', 'saturation', 'analog', 'vintage'],
  'neve 1073 preamp & eq':  ['eq', 'saturation', 'analog', 'vintage'],
  'neve 1081':              ['eq', 'comp', 'analog', 'vintage'],
  'neve 1084':              ['eq', 'saturation', 'analog', 'vintage'],
  'neve 33609':             ['comp', 'bus', 'analog', 'vintage'],
  'neve 88rs':              ['eq', 'comp', 'analog', 'vintage'],
  'neve 8078':              ['eq', 'analog', 'vintage'],
  'neve summing':           ['saturation', 'analog', 'vintage'],
  'ssl 4000 e series channel strip': ['eq', 'comp', 'analog', 'vintage'],
  'ssl 4000 g bus compressor': ['comp', 'bus', 'analog', 'vintage'],
  'ssl e channel strip':    ['eq', 'comp', 'analog', 'vintage'],
  'api 550a':               ['eq', 'analog', 'vintage'],
  'api 550b':               ['eq', 'analog', 'vintage'],
  'api 560':                ['eq', 'analog', 'vintage'],
  'api 2500 bus compressor': ['comp', 'bus', 'analog'],
  'manley massive passive stereo eq': ['eq', 'analog', 'vintage'],
  'manley voxbox channel strip': ['eq', 'comp', 'analog', 'vintage', 'tube'],
  'manley variable mu':     ['comp', 'bus', 'analog', 'vintage', 'tube'],
  'pultec eqp-1a':          ['eq', 'analog', 'vintage'],
  'pultec-pro':             ['eq', 'analog', 'vintage'],
  'fairchild 660':          ['comp', 'analog', 'vintage'],
  'fairchild 670':          ['comp', 'bus', 'analog', 'vintage'],
  'studer a800':            ['saturation', 'tape', 'analog', 'vintage'],
  'ampex atr-102':          ['saturation', 'tape', 'analog', 'vintage'],
  'moog multimode filter':  ['filter', 'analog', 'vintage'],
  'moog multimode filter se': ['filter', 'analog', 'vintage'],
  'lexicon 224':            ['reverb', 'vintage'],
  'lexicon 480l':           ['reverb', 'vintage'],
  'capitol chambers':       ['reverb', 'plate', 'vintage'],
  'emt 140':                ['reverb', 'plate', 'vintage'],
  'ocean way studios':      ['reverb', 'room', 'vintage'],
  'roland re-201':          ['delay', 'vintage', 'lo-fi'],
  'roland dimension d':     ['chorus', 'vintage'],
  'precision eq':           ['eq', 'mastering'],
  'precision limiter':      ['limiter', 'mastering'],
  'precision multiband':    ['multiband', 'mastering'],
  'precision maximizer':    ['limiter', 'mastering'],
  'precision de-esser':     ['de-esser', 'vocal', 'dynamic'],
  'cambridge eq':           ['eq'],
  'dbx 160 compressor':     ['comp', 'analog', 'vintage'],
  'helios type 69':         ['eq', 'saturation', 'analog', 'vintage'],
  'harrison 32c se':        ['eq', 'analog', 'vintage'],
  'harrison 32c':           ['eq', 'analog', 'vintage'],

  // ── Celemony / pitch tools ────────────────────────────────────────────────────
  'repitch':            ['pitch', 'vocal', 'utility'],

  // ── oeksound ─────────────────────────────────────────────────────────────────
  'soothe2':            ['eq', 'dynamic', 'vocal'],
  'soothe 2':           ['eq', 'dynamic', 'vocal'],
  'spiff':              ['transient', 'dynamic'],

  // ── Wavesfactory ─────────────────────────────────────────────────────────────
  'trackspacer':        ['sidechain', 'dynamic', 'eq'],

  // ── Tokyo Dawn ───────────────────────────────────────────────────────────────
  'nova':               ['eq', 'dynamic', 'comp'],
  'kotelnikov':         ['comp', 'dynamic'],
  'molot':              ['comp', 'analog', 'vintage'],
  'slow':               ['gate', 'ambient'],
  'prism':              ['eq', 'saturation'],
  'slick eq':           ['eq'],
  'transpire':          ['transient', 'dynamic'],

  // ── Zynaptiq ─────────────────────────────────────────────────────────────────
  'pitch map':          ['pitch', 'harmonic'],
  'wormhole':           ['reverb', 'pitch', 'distortion'],
  'unmix::drums':       ['drum', 'utility', 'spectral'],
  'morph':              ['spectral', 'vocal'],
  'unfilter':           ['eq', 'utility'],

  // ── Cableguys ────────────────────────────────────────────────────────────────
  'volumeshaper 6':     ['sidechain', 'dynamic'],
  'volumeshaper':       ['sidechain', 'dynamic'],
  'panshaper 3':        ['panning', 'sidechain'],
  'panshaper':          ['panning', 'sidechain'],
  'filtershaper core':  ['filter', 'sidechain'],
  'filtershaper':       ['filter', 'sidechain'],
  'halftime':           ['lo-fi', 'glitch'],
  'timeshaper 2':       ['glitch', 'sequencer'],
  'timeshaper':         ['glitch', 'sequencer'],
  'shaperbox 3':        ['multi-fx', 'sidechain'],
  'shaperbox 2':        ['multi-fx', 'sidechain'],

  // ── Glitchmachines ───────────────────────────────────────────────────────────
  'fracture xt':        ['glitch', 'granular'],
  'fracture':           ['glitch', 'sampler'],
  'polygon':            ['granular', 'sampler'],
  'quadrant':           ['glitch', 'sequencer'],
  'hysteresis':         ['delay', 'glitch'],
  'subvert':            ['distortion', 'glitch'],

  // ── Sugar Bytes ──────────────────────────────────────────────────────────────
  'effectrix':          ['multi-fx', 'glitch', 'sequencer'],
  'turnado':            ['multi-fx', 'filter'],
  'wow2':               ['filter', 'vintage'],
  'factory':            ['synth', 'wavetable'],
  'aparillo':           ['synth', 'fm'],
  'drum computer':      ['drum', 'sequencer'],
  'obscurium':          ['synth', 'granular'],
  'cyclop':             ['bass', 'synth'],

  // ── Reaktor-based / Monark ───────────────────────────────────────────────────
  'rounds':             ['synth', 'wavetable'],
  'flesh':              ['synth', 'sample-based'],
  'molekular':          ['multi-fx'],
  'polyplex':           ['drum', 'sample-based', 'granular'],
  'skanner xt':         ['synth', 'sample-based'],
  'newscool':           ['synth', 'lo-fi'],

  // ── Pianoteq ─────────────────────────────────────────────────────────────────
  'pianoteq 8':         ['piano', 'physical-modeling'],
  'pianoteq 7':         ['piano', 'physical-modeling'],
  'pianoteq':           ['piano', 'physical-modeling'],
  'chromaphone 3':      ['physical-modeling', 'percussive'],
  'chromaphone 2':      ['physical-modeling', 'percussive'],
  'ametrine':           ['physical-modeling', 'pluck'],

  // ── Spitfire Audio ───────────────────────────────────────────────────────────
  'spitfire audio bbc symphony orchestra': ['strings', 'brass', 'sample-based'],
  'bbc symphony orchestra':  ['strings', 'brass', 'sample-based'],
  'spitfire chamber strings': ['strings', 'sample-based'],
  'albion one':         ['strings', 'brass', 'sample-based', 'ambient'],
  'labs':               ['sample-based', 'ambient'],
  'hans zimmer strings': ['strings', 'sample-based'],
  'eric whitacre choir': ['vocal', 'choir', 'sample-based'],
  'originals frozen strings': ['strings', 'sample-based', 'ambient'],
  'originals epic brass': ['brass', 'sample-based'],

  // ── EastWest ─────────────────────────────────────────────────────────────────
  'hollywood orchestra': ['strings', 'brass', 'sample-based'],
  'hollywood strings':  ['strings', 'sample-based'],
  'hollywood brass':    ['brass', 'sample-based'],
  'hollywood choir':    ['vocal', 'choir', 'sample-based'],
  'hollywood diamonds': ['piano', 'sample-based'],
  'quantum leap':       ['sample-based'],
  'stormdrum':          ['drum', 'sample-based'],
  'silk':               ['strings', 'sample-based', 'ambient'],
  'voices of passion':  ['vocal', 'sample-based'],

  // ── Waldorf ──────────────────────────────────────────────────────────────────
  'nave':       ['synth', 'wavetable', 'additive'],
  'largo':      ['synth', 'wavetable', 'additive'],
  'attack':     ['drum', 'physical-modeling'],
  'lector':     ['vocoder'],

  // ── Korg ─────────────────────────────────────────────────────────────────────
  'ms-20':          ['synth', 'analog', 'vintage', 'filter'],
  'wavestation':    ['synth', 'wavetable', 'additive', 'vintage'],
  'polysix':        ['synth', 'analog', 'vintage', 'chorus'],
  'm1':             ['synth', 'sample-based', 'vintage'],
  'minilogue xd':   ['synth', 'analog'],
  'prologue':       ['synth', 'analog', 'wavetable'],
  'arp odyssey':    ['synth', 'analog', 'vintage'],

  // ── Roland / Juno ────────────────────────────────────────────────────────────
  'aira system-1':    ['synth', 'analog'],
  'juno-106':         ['synth', 'analog', 'vintage', 'chorus'],
  'jupiter-8':        ['synth', 'analog', 'vintage', 'pad'],
  'sh-2':             ['synth', 'analog', 'vintage', 'lead'],
  'd-50':             ['synth', 'sample-based', 'additive', 'vintage'],
  'jv-1080':          ['synth', 'sample-based', 'vintage'],

  // ── Dada Life ────────────────────────────────────────────────────────────────
  'sausage fattener':   ['saturation', 'distortion', 'dynamic'],
  'endless smile':      ['comp', 'saturation'],

  // ── Krotos ───────────────────────────────────────────────────────────────────
  'dehumaniser 2':      ['vocal', 'distortion'],
  'reformer pro':       ['granular', 'sample-based'],

  // ── Melda Production ─────────────────────────────────────────────────────────
  'mautopitch':         ['pitch', 'vocal'],
  'mcompressor':        ['comp', 'dynamic'],
  'mequalizer':         ['eq'],
  'mautoequalizer':     ['eq', 'dynamic'],
  'mdynamics':          ['comp', 'dynamic'],
  'mringmodulator':     ['ring-mod'],
  'mvibrato':           ['mod', 'vintage'],
  'mchorus':            ['chorus'],
  'mflanger':           ['flanger'],
  'mphaser':            ['phaser'],
  'mgranularmbfx':      ['granular'],
  'mspectraldelay':     ['delay', 'spectral'],
  'mnoisesuppressor':   ['noise', 'utility'],

  // ── ADPTR Audio ──────────────────────────────────────────────────────────────
  'metric ab':          ['utility', 'mastering'],
  'streamliner':        ['mastering', 'utility'],

  // ── Ableton Live — Audio Effects ─────────────────────────────────────────────
  'amp':                ['distortion', 'saturation', 'tube'],
  'auto filter':        ['filter', 'mod'],
  'auto pan':           ['panning'],
  'beat repeat':        ['glitch', 'sequencer'],
  'cabinet':            ['distortion', 'saturation'],
  'channel eq':         ['eq', 'filter'],
  'chorus-ensemble':    ['chorus'],
  'color limiter':      ['limiter', 'saturation'],
  'compressor':         ['comp', 'dynamic'],
  'corpus':             ['physical-modeling', 'filter'],
  'delay':              ['delay'],
  'drum buss':          ['drum', 'saturation', 'comp'],
  'dynamic tube':       ['saturation', 'tube', 'dynamic'],
  'echo':               ['delay', 'vintage'],
  'eq eight':           ['eq', 'filter'],
  'eq three':           ['eq', 'filter'],
  'erosion':            ['bitcrusher', 'noise'],
  'filter delay':       ['delay', 'filter'],
  'flanger':            ['flanger'],
  'frequency shifter':  ['pitch', 'ring-mod'],
  'gate':               ['gate', 'dynamic'],
  'glue compressor':    ['comp', 'bus', 'analog'],
  'grain delay':        ['granular', 'delay'],
  'hybrid reverb':      ['reverb', 'convolution'],
  'limiter':            ['limiter'],
  'looper':             ['utility', 'looper'],
  'multiband dynamics': ['comp', 'multiband', 'dynamic'],
  'overdrive':          ['distortion', 'saturation'],
  'pedal':              ['distortion', 'saturation'],
  'phaser':             ['phaser'],
  'phaser-flanger':     ['phaser', 'flanger'],
  'redux':              ['bitcrusher', 'lo-fi', 'noise'],
  'resonators':         ['physical-modeling', 'filter'],
  'reverb':             ['reverb', 'room'],
  'roar':               ['distortion', 'saturation'],
  'saturator':          ['saturation', 'distortion'],
  'shifter':            ['pitch', 'ring-mod'],
  'spectral resonator': ['spectral', 'physical-modeling'],
  'spectral time':      ['spectral', 'delay', 'reverb'],
  'spectrum':           ['utility'],
  'tuner':              ['utility'],
  'utility':            ['utility'],
  'vinyl distortion':   ['distortion', 'saturation', 'noise', 'vintage'],
  'vocoder':            ['vocoder'],
  'align delay':        ['delay', 'utility'],

  // ── Ableton Live — Instruments ───────────────────────────────────────────────
  'analog':             ['synth', 'analog'],
  'collision':          ['physical-modeling', 'percussive'],
  'drift':              ['synth', 'analog', 'wavetable'],
  'drum rack':          ['drum', 'sample-based'],
  'drum synthesizer':   ['drum', 'synth'],
  'electric':           ['keys', 'physical-modeling', 'vintage'],
  'impulse':            ['drum', 'sample-based'],
  'meld':               ['synth', 'analog'],
  'operator':           ['synth', 'fm', 'additive'],
  'sampler':            ['sample-based'],
  'simpler':            ['sample-based'],
  'tension':            ['physical-modeling', 'strings'],
  'wavetable':          ['synth', 'wavetable'],
  'instrument rack':    ['utility'],
  'audio effect rack':  ['utility'],

  // ── Ableton Live — MIDI Effects ──────────────────────────────────────────────
  'arpeggiator':        ['sequencer'],
  'chord':              ['sequencer', 'harmonic'],
  'midi effect rack':   ['utility'],
  'note length':        ['utility'],
  'pitch':              ['pitch', 'utility'],
  'random':             ['utility', 'sequencer'],
  'scale':              ['utility'],
  'strum':              ['sequencer'],
  'velocity':           ['utility', 'dynamic'],

  // ── Ableton Live — Max for Live (bundled with Suite) ─────────────────────────
  'lfo':                ['mod', 'utility'],
  'envelope follower':  ['mod', 'sidechain', 'utility'],
  'expression control': ['mod', 'utility'],
  'shaper':             ['mod', 'utility'],
  'convolution reverb': ['reverb', 'convolution'],
  'convolution reverb pro': ['reverb', 'convolution'],
  'note echo':          ['delay', 'sequencer'],
  'midi monitor':       ['utility'],
  'max for live':       ['utility'],

  // ── Aegean Music ─────────────────────────────────────────────────────────────
  'pitchproof':         ['pitch', 'harmonic'],
  'doppler dome':       ['pitch'],

  // ── AnalogObsession ──────────────────────────────────────────────────────────
  'comper':             ['comp', 'analog', 'vintage'],
  'lala':               ['comp', 'analog', 'vintage'],
  'fetish':             ['comp', 'analog', 'vintage'],
  'rnla':               ['comp', 'analog', 'vintage'],
  'buxom':              ['saturation', 'tube', 'analog', 'vintage'],
  'freq':               ['eq', 'analog', 'vintage'],
  'skew':               ['eq', 'analog', 'vintage'],
  'canopus':            ['reverb', 'vintage'],
  'cassette':           ['saturation', 'tape', 'lo-fi', 'vintage'],
  'rushtone':           ['saturation', 'tube', 'analog'],
  'channel':            ['eq', 'comp', 'analog', 'vintage'],
  'dent2':              ['distortion', 'saturation'],
  'deesser':            ['de-esser', 'vocal', 'dynamic'],
  'enhancer':           ['harmonic', 'exciter'],
  'push':               ['comp', 'saturation', 'analog'],
  'rone':               ['reverb', 'room'],
  'teote':              ['eq', 'dynamic'],
  'swiftly':            ['comp', 'analog'],
  'merica':             ['comp', 'bus', 'analog', 'vintage'],
  'bsteiner':           ['eq', 'analog', 'vintage'],
  'bclamp':             ['comp', 'analog', 'vintage'],

  // ── Apple (Logic Pro plugins) ─────────────────────────────────────────────────
  'space designer':     ['reverb', 'convolution'],
  'channel eq':         ['eq', 'filter'],
  'vintage b3':         ['organ', 'vintage'],
  'vintage electric piano': ['keys', 'vintage', 'physical-modeling'],
  'vintage clav':       ['keys', 'vintage', 'physical-modeling'],
  'es2':                ['synth', 'wavetable', 'additive'],
  'es e':               ['synth', 'analog'],
  'es m':               ['synth', 'analog'],
  'es p':               ['synth', 'analog'],
  'es1':                ['synth', 'analog'],
  'retro synth':        ['synth', 'analog', 'wavetable', 'fm', 'vintage'],
  'alchemy':            ['synth', 'sample-based', 'additive', 'granular', 'spectral'],
  'exs24':              ['sample-based'],
  'quick sampler':      ['sample-based'],
  'ultrabeat':          ['drum', 'synth'],
  'tape delay':         ['delay', 'tape', 'vintage'],
  'stereo delay':       ['delay'],
  'sample delay':       ['delay', 'utility'],
  'modulation delay':   ['delay', 'mod'],
  'pedalboard':         ['multi-fx', 'distortion'],
  'amp designer':       ['distortion', 'saturation'],
  'bass amp designer':  ['distortion', 'saturation', 'bass'],
  'direction mixer':    ['imager', 'utility'],
  'gain':               ['utility'],
  'i/o':                ['utility'],
  'exciter':            ['exciter', 'harmonic'],
  'enveloper':          ['transient', 'dynamic'],
  'noise gate':         ['gate', 'dynamic'],
  'adaptive limiter':   ['limiter', 'mastering'],
  'linear phase eq':    ['eq', 'mastering'],
  'multipressor':       ['comp', 'multiband', 'mastering'],
  'match eq':           ['eq', 'utility'],
  'pitch correction':   ['pitch', 'vocal'],
  'pitch shifter':      ['pitch'],
  'vocal transformer':  ['vocal', 'pitch', 'formant'],
  'ringshifter':        ['ring-mod', 'pitch'],
  'rotor cabinet':      ['organ', 'mod', 'vintage'],
  'tremolo':            ['tremolo'],
  'flanger':            ['flanger'],
  'phaser':             ['phaser'],
  'chorus':             ['chorus'],
  'spreader':           ['widener', 'chorus'],
  'sample alchemy':     ['synth', 'granular', 'sample-based'],

  // ── Audio Damage ─────────────────────────────────────────────────────────────
  'quanta 2':           ['synth', 'granular'],
  'quanta':             ['synth', 'granular'],
  'phosphor 3':         ['synth', 'additive'],
  'phosphor 2':         ['synth', 'additive'],
  'discord 4':          ['pitch', 'harmonic'],
  'discord3':           ['pitch', 'harmonic'],
  'enso':               ['looper', 'granular'],
  'kombinat tri':       ['distortion', 'multiband'],
  'replicant 3':        ['glitch', 'sequencer'],
  'replicant 2':        ['glitch', 'sequencer'],
  'rough rider 3':      ['comp', 'dynamic'],
  'rough rider plus':   ['comp', 'dynamic'],
  'dubstation 2':       ['delay', 'analog', 'vintage'],
  'eos 2':              ['reverb', 'room'],
  'adverb 2':           ['reverb', 'vintage'],
  'fuzz plus 3':        ['distortion', 'saturation'],
  'filterstation 2':    ['filter', 'vintage'],
  'bitcom':             ['bitcrusher', 'lo-fi'],
  'axon 2':             ['sequencer'],
  'dub station':        ['delay', 'analog', 'vintage'],

  // ── Audio Modeling ───────────────────────────────────────────────────────────
  'swam violin':        ['strings', 'physical-modeling'],
  'swam viola':         ['strings', 'physical-modeling'],
  'swam cello':         ['strings', 'physical-modeling'],
  'swam double bass':   ['strings', 'physical-modeling', 'bass'],
  'swam flute':         ['physical-modeling', 'woodwind'],
  'swam piccolo':       ['physical-modeling', 'woodwind'],
  'swam oboe':          ['physical-modeling', 'woodwind'],
  'swam clarinet':      ['physical-modeling', 'woodwind'],
  'swam bass clarinet': ['physical-modeling', 'woodwind'],
  'swam soprano saxophone': ['physical-modeling', 'woodwind'],
  'swam alto saxophone':    ['physical-modeling', 'woodwind'],
  'swam tenor saxophone':   ['physical-modeling', 'woodwind'],
  'swam baritone saxophone': ['physical-modeling', 'woodwind'],
  'swam trumpet':       ['brass', 'physical-modeling'],
  'swam flugelhorn':    ['brass', 'physical-modeling'],
  'swam trombone':      ['brass', 'physical-modeling'],
  'swam bass trombone': ['brass', 'physical-modeling'],
  'swam french horn':   ['brass', 'physical-modeling'],
  'swam tuba':          ['brass', 'physical-modeling'],

  // ── BABY Audio ───────────────────────────────────────────────────────────────
  'comeback kid':       ['delay', 'vintage'],
  'spaced out':         ['reverb', 'chorus', 'delay'],
  'i heart ny':         ['comp', 'parallel', 'drum'],
  'super vhs':          ['lo-fi', 'saturation', 'vintage'],
  'smooth operator':    ['eq', 'dynamic', 'comp'],
  'crystalline':        ['reverb', 'ambient'],
  'pitch drift':        ['pitch', 'vintage'],
  'transit':            ['filter', 'mod'],
  'ba-1':               ['synth', 'analog'],
  'parallel aggressor': ['comp', 'parallel', 'dynamic'],
  'magic switch':       ['chorus', 'widener', 'vintage'],
  'shadow hills':       ['comp', 'analog'],

  // ── Bertom ───────────────────────────────────────────────────────────────────
  'bertom denoiser':    ['noise', 'utility'],
  'phantom center':     ['imager', 'utility'],
  'bertom eq curve analyser': ['utility'],

  // ── D16 Group ────────────────────────────────────────────────────────────────
  'lush-101':           ['synth', 'analog', 'vintage'],
  'nepheton':           ['drum', 'vintage', 'analog'],
  'drumazon':           ['drum', 'vintage', 'analog'],
  'nithonat':           ['drum', 'vintage', 'analog'],
  'syntorus 2':         ['chorus', 'analog', 'vintage'],
  'syntorus':           ['chorus', 'analog', 'vintage'],
  'decimort 2':         ['bitcrusher', 'lo-fi', 'noise'],
  'decimort':           ['bitcrusher', 'lo-fi', 'noise'],
  'devastator':         ['comp', 'multiband', 'dynamic'],
  'fazortan 2':         ['phaser', 'vintage'],
  'fazortan':           ['phaser', 'vintage'],
  'frontier':           ['limiter', 'mastering'],
  'redoptor 2':         ['distortion', 'tube', 'vintage'],
  'toraverb 2':         ['reverb', 'room'],
  'toraverb':           ['reverb', 'room'],
  'bitcom':             ['bitcrusher', 'lo-fi'],
  'phoscyon 2':         ['drum', 'analog', 'vintage'],

  // ── Devious Machines ─────────────────────────────────────────────────────────
  'infiltrator 2':      ['multi-fx', 'filter', 'sequencer'],
  'infiltrator':        ['multi-fx', 'filter', 'sequencer'],
  'texture':            ['granular', 'ambient'],
  'duck':               ['sidechain', 'dynamic'],
  'pitch innovations harmonic shift': ['pitch', 'harmonic'],

  // ── Digital Suburban ─────────────────────────────────────────────────────────
  'deleight':           ['delay', 'multiband'],
  'percolate':          ['granular', 'ambient'],

  // ── Excite Audio ─────────────────────────────────────────────────────────────
  'lifeline expanse':   ['reverb', 'ambient'],
  'station':            ['reverb', 'vintage'],
  'lifeline console':   ['eq', 'comp', 'saturation'],
  'bloom':              ['filter', 'mod'],
  'lifeline andromeda': ['imager', 'reverb'],
  'lifeline pulsar':    ['tremolo', 'panning'],

  // ── Freakshow Industries ─────────────────────────────────────────────────────
  'mishby':             ['saturation'],
  'beastortion':        ['distortion'],
  'the dumpster fire':  ['distortion', 'lo-fi'],

  // ── IK Multimedia ────────────────────────────────────────────────────────────
  'amplitube 5':        ['multi-fx', 'distortion'],
  'amplitube 4':        ['multi-fx', 'distortion'],
  't-racks one':        ['mastering', 'comp', 'eq'],
  't-racks':            ['mastering', 'comp', 'eq'],
  'sampletank 4':       ['sample-based'],
  'syntronik 2':        ['synth', 'analog', 'vintage', 'sample-based'],
  'syntronik':          ['synth', 'analog', 'vintage', 'sample-based'],
  'modo bass 2':        ['bass', 'physical-modeling'],
  'modo bass':          ['bass', 'physical-modeling'],
  'modo drum':          ['drum', 'physical-modeling'],
  'black 76':           ['comp', 'analog', 'vintage'],
  'white 2a':           ['comp', 'analog', 'vintage'],
  'dyna-mu':            ['comp', 'analog', 'vintage', 'tube'],
  'equal':              ['eq'],
  'stealth limiter':    ['limiter', 'mastering'],
  'uno synth':          ['synth', 'analog'],

  // ── INA GRM ──────────────────────────────────────────────────────────────────
  'grm spaces':         ['reverb', 'spectral'],
  'grm doppler':        ['pitch'],
  'grm stamp':          ['spectral'],
  'grm spectral transform': ['spectral'],
  'grm bandpass':       ['filter', 'spectral'],
  'grm comb filter':    ['filter'],
  'grm delays':         ['delay', 'spectral'],

  // ── Klanghelm ────────────────────────────────────────────────────────────────
  'mjuc jr.':           ['comp', 'analog', 'vintage', 'tube'],
  'mjuc':               ['comp', 'analog', 'vintage', 'tube'],
  'dc1a':               ['comp', 'analog', 'dynamic'],
  'dc1a4':              ['comp', 'analog', 'dynamic'],
  'sdrr2':              ['saturation', 'distortion'],
  'sdrr':               ['saturation', 'distortion'],
  'ivgi':               ['saturation', 'analog'],
  'mbc':                ['comp', 'multiband'],
  'vumt':               ['utility'],
  'm/s ejection':       ['imager', 'utility'],

  // ── Lunacy Audio ─────────────────────────────────────────────────────────────
  'cube':               ['synth', 'granular', 'wavetable'],
  'lift':               ['pitch', 'harmonic'],

  // ── Madrona Labs ─────────────────────────────────────────────────────────────
  'aalto':              ['synth', 'physical-modeling'],
  'kaivo':              ['synth', 'physical-modeling', 'granular'],
  'virta':              ['spectral', 'pitch'],
  'sumu':               ['synth', 'additive', 'spectral'],
  'aaltoverb':          ['reverb', 'room'],

  // ── Plogue ───────────────────────────────────────────────────────────────────
  'chipsounds':         ['synth', 'lo-fi', 'vintage'],
  'chipspeech':         ['vocal', 'lo-fi'],
  'alter/ego':          ['vocal', 'synth'],
  'sforzando':          ['sample-based'],
  'bidule':             ['multi-fx', 'utility'],

  // ── Polyverse ────────────────────────────────────────────────────────────────
  'gatekeeper':         ['gate', 'sidechain', 'dynamic'],
  'manipulator':        ['vocal', 'pitch', 'formant'],
  'wider':              ['widener', 'imager'],
  'i wish':             ['reverb', 'ambient'],
  'comet delay':        ['delay', 'ambient'],
  'aftershock':         ['bass', 'distortion', 'multiband'],

  // ── SIR Audio Tools ──────────────────────────────────────────────────────────
  'sir3':               ['reverb', 'convolution'],
  'sir2':               ['reverb', 'convolution'],

  // ── sonible ──────────────────────────────────────────────────────────────────
  'smart:eq 4':         ['eq', 'dynamic'],
  'smart:eq 3':         ['eq', 'dynamic'],
  'smart:eq+':          ['eq', 'dynamic'],
  'smart:comp 2':       ['comp', 'dynamic'],
  'smart:comp':         ['comp', 'dynamic'],
  'smart:limit':        ['limiter', 'mastering'],
  'smart:reverb':       ['reverb'],
  'smart:delay':        ['delay'],
  'entropy:eq+':        ['eq', 'transient', 'dynamic'],
  'true:balance':       ['utility', 'mastering'],
  'pure:limit':         ['limiter', 'mastering'],

  // ── Sonic Academy ────────────────────────────────────────────────────────────
  'ana 2':              ['synth', 'wavetable'],
  'ana':                ['synth', 'wavetable'],
  'kick 2':             ['drum'],
  'kick 3':             ['drum'],
  'thump':              ['drum', 'bass'],

  // ── Sonic Charge ─────────────────────────────────────────────────────────────
  'microtonic':         ['drum', 'physical-modeling', 'synth'],
  'synplant 2':         ['synth', 'physical-modeling'],
  'synplant':           ['synth', 'physical-modeling'],
  'permut8':            ['glitch', 'bitcrusher'],
  'bitspeek':           ['vocoder', 'lo-fi'],

  // ── Synapse Audio ────────────────────────────────────────────────────────────
  'dune 3':             ['synth', 'wavetable', 'fm'],
  'dune 2':             ['synth', 'wavetable', 'fm'],
  'the legend':         ['synth', 'analog', 'vintage', 'lead'],
  'hydra':              ['synth'],

  // ── Toontrack ────────────────────────────────────────────────────────────────
  'superior drummer 3': ['drum', 'sample-based'],
  'superior drummer':   ['drum', 'sample-based'],
  'ezdrummer 3':        ['drum', 'sample-based'],
  'ezdrummer 2':        ['drum', 'sample-based'],
  'ezdrummer':          ['drum', 'sample-based'],
  'ezkeys 2':           ['piano', 'keys', 'sample-based'],
  'ezkeys':             ['piano', 'keys', 'sample-based'],
  'ezbass 2':           ['bass', 'sample-based'],
  'ezbass':             ['bass', 'sample-based'],
  'ezx':                ['drum', 'sample-based'],

  // ── UJAM ─────────────────────────────────────────────────────────────────────
  'virtual guitarist amber 2': ['strings', 'pluck', 'sample-based'],
  'virtual guitarist iron 2':  ['distortion', 'strings', 'pluck', 'sample-based'],
  'virtual guitarist silk 2':  ['strings', 'pluck', 'sample-based'],
  'virtual guitarist carbon':  ['strings', 'pluck', 'sample-based'],
  'virtual guitarist sparkle': ['strings', 'pluck', 'sample-based'],
  'virtual bassist royal':     ['bass', 'sample-based'],
  'virtual bassist mellow':    ['bass', 'sample-based'],
  'virtual bassist rowdy':     ['bass', 'sample-based'],
  'virtual bassist hollow':    ['bass', 'sample-based'],
  'virtual drummer phat':      ['drum', 'sample-based'],
  'virtual drummer deep':      ['drum', 'sample-based'],
  'virtual drummer solid':     ['drum', 'sample-based'],
  'usynth core':               ['synth'],
  'usynth drive':              ['synth', 'distortion'],
  'usynth dark':               ['synth', 'pad'],

  // ── Voxengo ──────────────────────────────────────────────────────────────────
  'span':               ['utility'],
  'span plus':          ['utility'],
  'elephant':           ['limiter', 'mastering'],
  'pha-979':            ['utility'],
  'polysaturator':      ['saturation', 'multiband'],
  'tempo delay':        ['delay', 'mod'],
  'correlometer':       ['utility'],
  'msed':               ['imager', 'utility'],
  'gliss eq':           ['eq', 'dynamic'],
  'marquis compressor': ['comp', 'analog'],
  'sobor':              ['reverb'],
  'voxformer':          ['vocal', 'comp', 'eq', 'de-esser'],
  'crunchessor':        ['comp', 'saturation'],
  'deft compressor':    ['comp', 'dynamic'],
  'drumformer':         ['drum', 'comp', 'transient'],
  'curveeq':            ['eq'],
  'latency delay':      ['utility', 'delay'],
  'recorder':           ['utility'],

  // ── Misc ─────────────────────────────────────────────────────────────────────
  'soundtoys 5':        ['multi-fx'],
  'vst amp rack':       ['distortion'],

  // ── Dmitry Sches ─────────────────────────────────────────────────────────────
  'thorn':              ['synth', 'wavetable', 'additive'],

  // ── AudioThing ───────────────────────────────────────────────────────────────
  'springs':            ['reverb', 'vintage', 'analog'],
  'outer space':        ['delay', 'reverb', 'vintage', 'lo-fi'],
  'reels':              ['saturation', 'tape', 'vintage', 'lo-fi'],
  'wires':              ['delay', 'reverb', 'lo-fi', 'vintage'],
  'fog convolver':      ['reverb', 'convolution'],
  'noises':             ['noise'],
  'mantis':             ['tremolo', 'vintage'],
  'valves':             ['saturation', 'tube', 'vintage'],

  // ── Black Salt Audio ─────────────────────────────────────────────────────────
  'kounterpoint':       ['delay', 'spectral'],
  'magnetite':          ['saturation', 'tape', 'vintage'],

  // ── Denise Audio ─────────────────────────────────────────────────────────────
  'dragon fire':        ['distortion'],
  'perfect plate xl':   ['reverb', 'plate'],
  'noize':              ['noise'],
  'animate':            ['gate', 'sequencer'],
  'beast':              ['distortion', 'saturation'],

  // ── Acustica Audio ───────────────────────────────────────────────────────────
  'sand 4':             ['eq', 'analog', 'vintage'],
  'rose 4':             ['comp', 'analog', 'vintage'],
  'ivory 4':            ['eq', 'analog', 'vintage'],
  'ultramarine 4':      ['eq', 'comp', 'analog', 'vintage'],
  'jade 4':             ['comp', 'analog', 'vintage'],
  'navy 4':             ['eq', 'analog', 'vintage'],

  // ── Newfangled Audio ─────────────────────────────────────────────────────────
  'elevate mastering limiter': ['limiter', 'mastering', 'multiband'],
  'elevate':            ['limiter', 'mastering', 'multiband'],
  'saturate':           ['saturation', 'distortion', 'multiband'],
  'recur':              ['delay', 'reverb'],
  'pendulate':          ['synth', 'analog'],
  'generate':           ['synth', 'fm'],

  // ── Goodhertz ────────────────────────────────────────────────────────────────
  'vulf compressor':    ['comp', 'saturation', 'lo-fi', 'vintage'],
  'lossy':              ['lo-fi', 'noise'],
  'wow control':        ['mod', 'saturation', 'vintage'],
  'canopener studio':   ['imager', 'utility'],
  'trem control':       ['tremolo'],
  'faraday limiter':    ['limiter', 'saturation'],
  'tone control':       ['eq', 'filter'],
  'megaverb':           ['reverb', 'lo-fi'],
  'midside':            ['imager', 'utility'],
  'panpot':             ['panning', 'utility'],
  'mailbox':            ['delay', 'lo-fi'],

  // ── Ableton Live — new instruments (Live 12) ─────────────────────────────────
  'bass':               ['synth', 'bass'],
  'drum sampler':       ['drum', 'sample-based'],
  'granulator iii':     ['granular'],
  'granulator ii':      ['granular'],
  'emit':               ['granular', 'ambient'],
  'poli':               ['synth', 'sample-based'],
  'tree tone':          ['physical-modeling'],
  'vector fm':          ['synth', 'fm'],
  'vector grain':       ['synth', 'granular'],
  'ds clang':           ['drum', 'synth'],
  'ds clap':            ['drum', 'synth'],
  'ds cymbal':          ['drum', 'synth'],
  'ds fm':              ['drum', 'synth', 'fm'],
  'ds hh':              ['drum', 'synth'],
  'ds kick':            ['drum', 'synth'],
  'ds snare':           ['drum', 'synth'],
  'ds tom':             ['drum', 'synth'],

  // ── Ableton Live — new audio effects (Live 12) ───────────────────────────────
  'auto pan-tremolo':   ['panning', 'tremolo'],
  'auto shift':         ['pitch', 'harmonic'],
  'gated delay':        ['delay', 'gate'],
  'performer':          ['glitch', 'sequencer'],
  'pitch hack':         ['pitch', 'glitch'],
  'pitchloop89':        ['pitch', 'delay', 'lo-fi'],
  'prearranger':        ['utility'],
  're-enveloper':       ['transient', 'dynamic'],
  'spectral blur':      ['spectral', 'ambient'],
  'surround panner':    ['panning', 'utility'],
  'variations':         ['sequencer', 'utility'],
  'vector delay':       ['delay', 'mod'],
  'vector map':         ['utility', 'mod'],
  'arrangement looper': ['utility', 'looper'],
  'cv clock in':        ['utility'],
  'cv clock out':       ['utility'],
  'cv envelope follower': ['mod', 'utility'],
  'cv in':              ['utility'],
  'cv lfo':             ['mod', 'utility'],
  'cv shaper':          ['mod', 'utility'],
  'cv utility':         ['utility'],
  'cv instrument':      ['utility'],
  'cv triggers':        ['utility'],
  'external instrument':['utility'],
  'external audio effect': ['utility'],
  'ir measurement device': ['utility'],

  // ── Ableton Live — new MIDI effects (Live 12) ────────────────────────────────
  'bouncy notes':       ['sequencer'],
  'cc control':         ['utility'],
  'envelope midi':      ['mod', 'utility'],
  'expressive chords':  ['sequencer', 'harmonic'],
  'melodic steps':      ['sequencer'],
  'microtuner':         ['utility', 'pitch'],
  'mpe control':        ['utility'],
  'rhythmic steps':     ['sequencer'],
  'rotating rhythm generator': ['sequencer'],
  'shaper midi':        ['mod', 'utility', 'sequencer'],
  'sq sequencer':       ['sequencer'],
  'step arp':           ['sequencer', 'arp'],

  // ── Kilohearts — kHs snap-ins ────────────────────────────────────────────────
  'khs shaper':         ['mod', 'utility'],
  'khs stereo':         ['imager', 'utility'],
  'khs bitcrush':       ['bitcrusher', 'lo-fi'],
  'khs transient shaper': ['transient', 'dynamic'],
  'khs comb filter':    ['filter'],
  'khs haas':           ['widener', 'imager'],
  'khs formant filter': ['filter', 'formant', 'vocal'],
  'khs frequency shifter': ['pitch', 'ring-mod'],
  'khs trance gate':    ['gate', 'sidechain', 'sequencer'],
  'khs ring mod':       ['ring-mod'],
  'khs reverser':       ['glitch'],
  'khs resonator':      ['filter', 'physical-modeling'],
  'khs ladder filter':  ['filter', 'analog'],
  'khs chorus':         ['chorus'],
  'khs compressor':     ['comp', 'dynamic'],
  'khs delay':          ['delay'],
  'khs distortion':     ['distortion', 'saturation'],
  'khs ensemble':       ['chorus'],
  'khs flanger':        ['flanger'],
  'khs gate':           ['gate', 'dynamic'],
  'khs limiter':        ['limiter'],
  'khs nonlinear filter': ['filter', 'distortion'],
  'khs pitch shifter':  ['pitch'],
  'khs reverb':         ['reverb'],
  'khs tape stop':      ['glitch', 'mod'],

  // ── UADx ─────────────────────────────────────────────────────────────────────
  'uadx pure plate reverb':             ['reverb', 'plate'],
  'uadx pultec meq-5 eq':               ['eq', 'analog', 'vintage'],
  'uadx verve analog machines essentials': ['saturation', 'analog', 'vintage'],
  'uadx galaxy tape echo':              ['delay', 'tape', 'vintage'],
  'uadx la-2 compressor':               ['comp', 'analog', 'vintage'],
  'uadx polymax synth':                 ['synth', 'wavetable'],
  'uadx la-2a gray compressor':         ['comp', 'analog', 'vintage'],
  'uadx century tube channel strip':    ['eq', 'comp', 'tube', 'analog'],
  'uadx pultec hlf-3c eq':              ['eq', 'analog', 'vintage'],
  'uadx oxide tape recorder':           ['saturation', 'tape', 'analog', 'vintage'],
  'uadx la-2a silver compressor':       ['comp', 'analog', 'vintage'],
  'uadx pultec eqp-1a eq':              ['eq', 'analog', 'vintage'],
  'uadx 1176 rev a limiting amp':       ['comp', 'analog', 'vintage'],
  'uadx neve 1073 preamp & eq':         ['eq', 'saturation', 'analog', 'vintage'],
  'uadx ssl e channel strip':           ['eq', 'comp', 'analog', 'vintage'],

  // ── SPL (via Plugin Alliance) ─────────────────────────────────────────────────
  'spl free ranger':            ['eq', 'analog'],
  'spl twintube':               ['saturation', 'tube', 'analog'],
  'spl iron':                   ['comp', 'saturation', 'analog', 'vintage'],
  'spl mo-verb plus':           ['reverb'],
  'spl drumxchanger':           ['drum', 'utility'],
  'spl eq ranger plus':         ['eq', 'analog'],
  'spl passeq':                 ['eq', 'analog', 'vintage'],
  'spl passeq single':          ['eq', 'analog', 'vintage'],
  'spl de-verb plus':           ['reverb', 'utility'],
  'spl de-esser':               ['de-esser', 'vocal', 'dynamic'],
  'spl de-esser dual-band':     ['de-esser', 'vocal', 'dynamic', 'multiband'],
  'spl hawkeye':                ['utility', 'mastering'],
  'spl attacker plus':          ['transient', 'dynamic'],
  'spl pq':                     ['eq', 'analog', 'vintage'],
  'spl vitalizer mk2-t':        ['exciter', 'harmonic', 'saturation'],
  'spl transient designer plus':['transient', 'dynamic'],

  // ── sonible — alt naming (without colon) ─────────────────────────────────────
  'smartcomp':          ['comp', 'dynamic'],
  'smarteq 3':          ['eq', 'dynamic'],
  'smarteq3':           ['eq', 'dynamic'],
  'smartreverb':        ['reverb'],
  'smartdelay':         ['delay'],
  'smartlimit':         ['limiter', 'mastering'],
  'smart:eq 4':         ['eq', 'dynamic'],

  // ── Arturia — new/alt names ───────────────────────────────────────────────────
  'cs-80 v4':           ['synth', 'analog', 'vintage', 'pad'],
  'mini v4':            ['synth', 'analog', 'vintage', 'lead'],
  'korg ms-20 v':       ['synth', 'analog', 'vintage', 'filter'],
  'vocoder v':          ['vocoder', 'synth'],
  'pitch shifter-910':  ['pitch', 'vintage'],
  'efx ambient':        ['reverb', 'ambient'],

  // ── FabFilter — prefixed/mono variants ───────────────────────────────────────
  'fabfilter pro-q 4':  ['eq', 'filter'],
  'fabfilter pro-q 3':  ['eq', 'filter'],
  'fabfilter pro-c 2':  ['comp', 'dynamic'],
  'fabfilter pro-l 2':  ['limiter', 'mastering'],
  'fabfilter pro-r 2':  ['reverb', 'room', 'plate'],
  'fabfilter pro-ds':   ['de-esser', 'vocal', 'dynamic'],
  'fabfilter pro-g':    ['gate', 'dynamic'],
  'fabfilter pro-mb':   ['comp', 'multiband', 'dynamic'],
  'fabfilter saturn 2': ['saturation', 'distortion', 'multiband'],
  'fabfilter timeless 3': ['delay', 'filter'],
  'fabfilter volcano 3':  ['filter', 'sequencer'],
  'fabfilter twin 3':   ['synth', 'filter', 'additive'],
  'fabfilter micro':    ['synth', 'filter'],
  'fabfilter one':      ['synth', 'sample-based', 'filter'],
  'simplon':            ['filter'],

  // ── Xfer — new versions ───────────────────────────────────────────────────────
  'serum 2':            ['synth', 'wavetable', 'granular'],
  'serum 2 fx':         ['filter', 'eq', 'multi-fx'],
  'lfotool':            ['mod', 'utility', 'sidechain'],

  // ── iZotope — prefixed ────────────────────────────────────────────────────────
  'izotope trash 2':    ['distortion', 'multiband'],
  'vinyl':              ['saturation', 'lo-fi', 'noise', 'vintage'],

  // ── BABY Audio ───────────────────────────────────────────────────────────────
  'ihny-2':             ['comp', 'saturation'],
  'humanoid':           ['vocal', 'pitch'],
  'atoms':              ['synth', 'wavetable'],
  'beam':               ['mod', 'spectral'],

  // ── Dada Life ────────────────────────────────────────────────────────────────
  'eternal return':     ['reverb', 'delay'],
  'wide awake':         ['comp', 'saturation'],
  'space in-your-face': ['reverb', 'imager'],
  'sausagefattener':    ['saturation', 'distortion', 'dynamic'],

  // ── Polyverse — additional ────────────────────────────────────────────────────
  'filtron':            ['filter', 'vintage'],
  'filterverse':        ['filter', 'spectral'],
  'supermodal':         ['filter', 'physical-modeling'],
  'comet':              ['delay', 'ambient'],

  // ── u-he — additional ────────────────────────────────────────────────────────
  'runciter':           ['filter', 'vintage'],
  'twangstrom':         ['reverb', 'spring', 'vintage'],

  // ── Antares — additional ──────────────────────────────────────────────────────
  'auto-tune vocodist': ['vocoder', 'vocal'],
  'auto-tune slice':    ['pitch', 'vocal', 'glitch'],
  'auto-tune vocal eq': ['eq', 'vocal'],
  'avox warm':          ['saturation', 'vocal'],

  // ── Tokyo Dawn — prefixed ─────────────────────────────────────────────────────
  'tdr kotelnikov':     ['comp', 'dynamic'],
  'tdr nova':           ['eq', 'dynamic', 'comp'],
  'tdr molot':          ['comp', 'analog', 'vintage'],
  'tdr slick eq':       ['eq'],
  'tdr feedback compressor ii': ['comp', 'dynamic'],

  // ── Unfiltered Audio (Plugin Alliance) ───────────────────────────────────────
  'unfiltered audio silo':      ['reverb', 'granular'],
  'unfiltered audio dent 2':    ['distortion', 'saturation'],
  'unfiltered audio specops':   ['spectral'],
  'unfiltered audio fault':     ['distortion', 'glitch'],
  'unfiltered audio zip':       ['comp', 'dynamic'],
  'unfiltered audio bass mint': ['bass', 'filter'],

  // ── Plugin Alliance — additional ─────────────────────────────────────────────
  'bx_rockrack v3 player':  ['distortion'],
  'bx_solo':                ['utility'],
  'bx_cleansweep v2':       ['filter', 'eq', 'utility'],
  'bx_masterdesk classic':  ['mastering', 'comp', 'eq'],
  'ms-20fx':                ['filter', 'analog', 'vintage'],
  'schoeps double ms':      ['imager', 'utility'],

  // ── Wavegrove ────────────────────────────────────────────────────────────────
  'vastaus':            ['reverb', 'granular'],

  // ── Freakshow Industries — additional ────────────────────────────────────────
  'mouthofsorrow':      ['distortion'],
  'mouth of sorrow':    ['distortion'],
  'pocketdimension':    ['delay', 'lo-fi'],
  'pocket dimension':   ['delay', 'lo-fi'],
  'dreameater':         ['reverb', 'ambient'],
  'dream eater':        ['reverb', 'ambient'],
  'backmask':           ['glitch', 'pitch'],

  // ── Synapse Audio — additional ────────────────────────────────────────────────
  'dune 3':             ['synth', 'wavetable', 'fm'],

  // ── SIR Audio Tools ──────────────────────────────────────────────────────────
  'standardclip':       ['limiter', 'clipper'],
  'standard clip':      ['limiter', 'clipper'],

  // ── Bertom ───────────────────────────────────────────────────────────────────
  'denoiser classic':   ['noise', 'utility'],
  'air frequency shaper': ['eq', 'exciter', 'harmonic'],

  // ── Steven Atkinson ──────────────────────────────────────────────────────────
  'neuralampenmodeler': ['distortion'],
  'neural amp modeler': ['distortion'],
  'neuralampmodeler':   ['distortion'],

  // ── Spectral Plugins ─────────────────────────────────────────────────────────
  'ocs-45':             ['synth', 'analog', 'vintage'],
  'pancz':              ['transient', 'dynamic'],
  'spacer':             ['reverb', 'room'],

  // ── plugdata ─────────────────────────────────────────────────────────────────
  'plugdata':           ['multi-fx', 'utility'],
  'plugdata-fx':        ['multi-fx', 'utility'],

  // ── Stepwise ─────────────────────────────────────────────────────────────────
  'sinusoidal shaped filter': ['filter', 'spectral'],
  'bin scrambler':      ['glitch', 'spectral'],
  'frequency magnet':   ['filter'],
  'spectral gate':      ['gate', 'spectral'],
  'phase lock':         ['utility', 'spectral'],

  // ── Michael Norris (spectral tools) ──────────────────────────────────────────
  'super filterbank':          ['filter', 'spectral'],
  'spectral partial glide':    ['spectral', 'pitch'],
  'spectral freezing':         ['spectral', 'ambient'],
  'spectral stretch':          ['spectral', 'stretch'],
  'spectral shimmer':          ['spectral', 'reverb'],
  'spectral emergence':        ['spectral'],
  'spectral pitch shift':      ['spectral', 'pitch'],
  'spectral weave':            ['spectral'],
  'spectral granulation':      ['spectral', 'granular'],
  'idee fixer':                ['spectral'],
  'spectral averaging':        ['spectral', 'ambient'],
  'spectral blurring':         ['spectral', 'ambient'],
  'spectral bin shift':        ['spectral', 'pitch'],
  'spectral harmonizer':       ['spectral', 'pitch', 'harmonic'],
  'spectral tracing':          ['spectral'],
  'spectral gliding filters':  ['spectral', 'filter'],
  'spectral gate and hold':    ['spectral', 'gate'],
  'spectral dronemaker':       ['spectral', 'ambient'],
  'spectral pulsing':          ['spectral', 'mod'],
  'spectral filterbank':       ['spectral', 'filter'],
  'grain streamer':            ['granular'],
  'spectral shuffle':          ['spectral', 'glitch'],

  // ── DataMind Audio ────────────────────────────────────────────────────────────
  'concatenator':       ['glitch', 'granular'],

  // ── Phase Fiasco ─────────────────────────────────────────────────────────────
  'tape fiasco':        ['saturation', 'tape', 'lo-fi', 'vintage'],

  // ── Sonosaurus ───────────────────────────────────────────────────────────────
  'paulxstretch':       ['spectral', 'stretch', 'ambient'],

  // ── GRM Tools ────────────────────────────────────────────────────────────────
  'grm tools atelier':  ['spectral'],
  'grm tools classic':  ['spectral'],

  // ── Misc ─────────────────────────────────────────────────────────────────────
  'dexed':              ['synth', 'fm', 'vintage'],
  'flechtwerk':         ['sequencer'],
  'minimetersserver':   ['utility'],
  'dodo midi':          ['utility', 'sequencer'],
  'splice bridge':      ['utility', 'sample-based'],
  'console recall':     ['utility'],

  // name variants (CamelCase, no-space) ─────────────────────────────────────────
  'dehumaniser simple monsters': ['vocal', 'distortion'],
  'dehumanisersimplemonsters':   ['vocal', 'distortion'],
  'roughrider3':        ['comp', 'dynamic'],
  'decimort2':          ['bitcrusher', 'lo-fi', 'noise'],
  'alterego':           ['vocal', 'synth'],
  'dumpster fire':      ['distortion', 'lo-fi'],
  'pitchmonster':       ['pitch', 'harmonic'],
  'h-delay mono':       ['delay', 'vintage'],
  'h-delay stereo':     ['delay', 'vintage'],
  'h-delay mono/stereo':['delay', 'vintage'],

  'elastik 3':          ['sample-based'],
  'elastik':            ['sample-based'],
  'microtonic multi':   ['drum', 'physical-modeling', 'synth'],
  'motion harmonic':    ['harmonic', 'mod'],
  'neutone morpho':     ['spectral', 'vocal'],
  'lurssen mastering console': ['mastering', 'comp', 'eq'],
  'vowel changer formant filter': ['filter', 'formant', 'vocal'],
  'swam variflute':     ['physical-modeling', 'woodwind'],
  'swam cello 3':       ['physical-modeling', 'strings'],
  'wavewarper 2':       ['granular'],
  'wavewarper':         ['granular'],

  // ── UJAM Finisher series ─────────────────────────────────────────────────────
  'fin-fluxx':          ['filter', 'mod'],
  'fin-dynamo':         ['saturation', 'distortion'],
  'fin-boost':          ['harmonic', 'saturation', 'exciter'],
  'fin-neo':            ['mod'],
  'fin-vood':           ['saturation', 'distortion'],
  'fin-retro':          ['saturation', 'vintage'],

};
